### ISSUE TITLE
Unraid template

### ISSUE THREAD

**Issue by nwithan8** [nickshanks347/monitarr#2]
I went ahead and made an Unraid template for this so users can easily install this Docker container from the Community Apps Store, should be live in a few hours.

**Comment by DinoHorvat96** [comment]
Unsure if it's the Unraid template or the code, but the environment variables are not being recognized at all. The API keys are "undefined", despite being correctly set.

`⨯ TypeError: Failed to parse URL from undefined/api/v3/queue?apikey=undefined
    at <unknown> (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:5640)
    at H (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:11068)
    at <unknown> (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:13686)
    at <unknown> (/app/node_modules/next/dist/server/lib/trace/tracer.js:171:36)
    at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    ... 2 lines matching cause stack trace ...
    at ProxyTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at <unknown> (/app/node_modules/next/dist/server/lib/trace/tracer.js:153:103) {
  [cause]: TypeError: Invalid URL
      at <unknown> (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:5640)
      at H (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:11068)
      at <unknown> (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:13686)
      at <unknown> (/app/node_modules/next/dist/server/lib/trace/tracer.js:171:36)
      at NoopContextManager.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
      at ContextAPI.with (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
      at NoopTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
      at ProxyTracer.startActiveSpan (/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854) {
    code: 'ERR_INVALID_URL',
    input: 'undefined/api/v3/queue?apikey=undefined'
  }`

![image](https://github.com/user-attachments/assets/5b877f6a-bb16-413b-8ee3-120117320841)

**Comment by nwithan8** [comment]
Oops, thanks, fixing and pushing an update

**Comment by Healzangels** [comment]
Thanks for sharing!

**Comment by AzrelixJ** [comment]
Not sure if this is related, but unable to get this to work on UNRAID.  any suggestions?

 ⨯ SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at async p (/app/.next/server/app/api/radarr/downloads/route.js:1:803)
    at async te.do (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17826)
    at async te.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:22492)
    at async doRender (/app/node_modules/next/dist/server/base-server.js:1455:42)
